version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-exchange-bot
    restart: unless-stopped
    volumes:
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - LOG_FILE=/app/logs/bot.log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 